def diagram(turns):
    
    if turns == 9:
        print("      ")
        print("            ")        
        print("             ")            
        print("             ")
        print("             ")
        print("             ")
        print("----")
    elif turns == 8:
        print("      ")
        print("|            ")      
        print("|             ")
        print("|             ")
        print("|             ")
        print("|             ")
        print("----")    
    elif turns == 7:
        print("________      ")
        print("|            ")
        print("|           ")
        print("|             ")
        print("|             ")
        print("|             ")
        print("----")
    elif turns == 6:
        print("________      ")            
        print("|      |      ")
        print("|            ")
        print("|            ")
        print("|             ")        
        print("|             ")
        print("----")

    elif turns == 5:
        print("________      ")
        print("|      |      ")
        print("|      0      ")            
        print("|           ")        
        print("|             ")
        print("|             ")            
        print("----")
    elif turns == 4:
        print("________      ")            
        print("|      |      ")
        print("|      0      ")
        print("|      |     ")
        print("|             ")
        print("|             ")
        print("----")
    elif turns == 3:
        print("________      ")
        print("|      |      ")            
        print("|      0      ")
        print("|     /|     ")
        print("|           ")
        print("|             ")
        print("----")
    elif turns == 2:
        print("________      ")
        print("|      |      ")
        print("|      0      ")
        print("|     /|\\     ")
        print("|           ")
        print("|             ")
        print("----")
    elif turns == 1:
        print("________      ")            
        print("|      |      ")
        print("|      0      ")
        print("|     /|\\     ")            
        print("|     /     ")
        print("|             ")
        print("----")        
    elif turns == 0:
        print("________      ")
        print("|      |      ")
        print("|      0      ")
        print("|     /|\\    ")
        print("|     / \\    ")
        print("|             ")
        print("----")
        print("You loose")